name: pages-deploy

on:
  workflow_dispatch:
  push:
    paths:
      - "index.html"
      - "main.js"
      - "*.css"
      - "input/*.xlsx"

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy openpyxl

      - name: Run data processing
        run: python process.py

      - name: Prepare site files
        run: |
          mkdir deploy
          cp index.html main.js deploy/
          cp output/Batting.csv output/Pitching.csv output/Fielding.csv deploy/

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
